name: Generate Starred Repos Report

on:
  schedule:
    - cron: '0 7 * * 1'  # tous les lundis à 07h00 UTC
  workflow_dispatch:     # exécutable manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Generate Markdown Table
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python stars_by_category.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add stars.md
          git commit -m "Update stars.md" || echo "No changes to commit"
          git push
